// Generates src/generated/* from api/openapi.yaml and skill.md so the Worker validates requests
// against the same schemas the reviewers probe. Run before typecheck, dev and deploy.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { parse } from 'yaml';

const doc = parse(readFileSync('api/openapi.yaml', 'utf8'));
const skill = readFileSync('skill.md', 'utf8');
const frontMatter = /^---\r?\n([\s\S]*?)\r?\n---/.exec(skill);
const skillVersion = /version:\s*([^\r\n]+)/.exec(frontMatter?.[1] ?? '')?.[1]?.trim() ?? '0';

mkdirSync('src/generated', { recursive: true });
writeFileSync('src/generated/openapi.json', JSON.stringify(doc));
writeFileSync('src/generated/schemas.json', JSON.stringify(doc.components.schemas));
writeFileSync(
  'src/generated/skill.ts',
  `// generated by scripts/build-schemas.mjs from skill.md and api/openapi.yaml\n` +
    `export const SKILL_MD: string = ${JSON.stringify(skill)};\n` +
    `export const SKILL_VERSION = ${JSON.stringify(skillVersion)};\n` +
    `export const API_VERSION = ${JSON.stringify(doc.info.version)};\n`,
);
console.log(`generated: ${Object.keys(doc.components.schemas).length} schemas, api ${doc.info.version}, skill ${skillVersion}`);
