"""Cross-check both implementations against an independent sumset oracle.

No network. Optional --reference-cnf verifies the baseline against the CNF
generated by the separately retrieved, reviewed Heule Schur-encode.c.
"""
import argparse
import base64
import hashlib
import itertools
import json
import random
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True
from verify import verify, verify_bytes
from build_baseline import build

ROOT = Path(__file__).resolve().parent


def oracle(colors):
    groups = [{i + 1 for i, c in enumerate(colors) if c == color} for color in range(6)]
    return all(not any(x + y in group for x in group for y in group) for group in groups)


def witness_is_real(result, colors):
    if 'counterexample' not in result:
        return True
    x, y, z = result['counterexample']
    return 1 <= x <= len(colors) and 1 <= y <= len(colors) and z == x + y <= len(colors) and colors[x - 1] == colors[y - 1] == colors[z - 1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--reference-cnf', type=Path)
    ap.add_argument('--output', type=Path, default=ROOT / 'validation.json')
    args = ap.parse_args()
    baseline_bytes = (ROOT / 'baseline-536.json').read_bytes()
    baseline = json.loads(baseline_bytes)
    assert build() == baseline
    assert hashlib.sha256(baseline_bytes).hexdigest() == '968f91177ddf7cbe9ce0347c8f2be089c54a6b648c387a6080cbec1237636010'
    cases = []
    def add(name, colors):
        cases.append(dict(name=name, artifact=dict(format_version=1, n=len(colors), colors=list(colors)), expected=oracle(colors)))

    for n in range(1, 6):
        for colors in itertools.product(range(6), repeat=n):
            add(f'exhaustive-n{n}-{len(cases)}', colors)
    exhaustive_count = len(cases)
    rng = random.Random(20260907)
    for i in range(300):
        add(f'random-{i}', [rng.randrange(6) for _ in range(rng.randrange(1, 81))])
    for n in range(1, 537):
        add(f'baseline-prefix-{n}', baseline['colors'][:n])
    mutation_start = len(cases)
    for index, old in enumerate(baseline['colors']):
        for color in range(6):
            if color == old: continue
            changed = list(baseline['colors']); changed[index] = color
            add(f'one-color-mutation-{index + 1}-{color}', changed)
    mutations = cases[mutation_start:]

    raw_cases = []
    def raw(name, value, expected=False):
        data = value if isinstance(value, bytes) else value.encode()
        raw_cases.append(dict(name=name, raw_b64=base64.b64encode(data).decode(), expected=expected))
    raw('valid-singleton', '{"format_version":1,"n":1,"colors":[0]}', True)
    raw('integral-json-numbers', '{"format_version":1.0,"n":1e0,"colors":[0.0]}', True)
    raw('escaped-valid-key', '{"format_version":1,"\\u006e":1,"colors":[0]}', True)
    raw('doubling-is-forbidden', '{"format_version":1,"n":2,"colors":[0,0]}')
    raw('unequal-summands-forbidden', '{"format_version":1,"n":5,"colors":[0,1,1,0,1]}')
    for name, value in {
        'empty': '', 'truncated': '{', 'null': 'null', 'array-root': '[]',
        'missing-n': '{"format_version":1,"colors":[0]}',
        'unknown-field': '{"format_version":1,"n":1,"colors":[0],"extra":1}',
        'duplicate-n': '{"format_version":1,"n":2,"n":1,"colors":[0]}',
        'escaped-duplicate-n': '{"format_version":1,"n":2,"\\u006e":1,"colors":[0]}',
        'bool-n': '{"format_version":1,"n":true,"colors":[0]}',
        'bool-version': '{"format_version":true,"n":1,"colors":[0]}',
        'bool-color': '{"format_version":1,"n":1,"colors":[false]}',
        'fraction-n': '{"format_version":1,"n":1.5,"colors":[0]}',
        'fraction-color': '{"format_version":1,"n":1,"colors":[0.5]}',
        'negative-n': '{"format_version":1,"n":-1,"colors":[]}',
        'zero-n': '{"format_version":1,"n":0,"colors":[]}',
        'over-cap-n': '{"format_version":1,"n":10001,"colors":[]}',
        'negative-color': '{"format_version":1,"n":1,"colors":[-1]}',
        'color-six': '{"format_version":1,"n":1,"colors":[6]}',
        'string-color': '{"format_version":1,"n":1,"colors":["0"]}',
        'null-color': '{"format_version":1,"n":1,"colors":[null]}',
        'object-colors': '{"format_version":1,"n":1,"colors":{"0":0}}',
        'short-colors': '{"format_version":1,"n":2,"colors":[0]}',
        'long-colors': '{"format_version":1,"n":1,"colors":[0,1]}',
        'wrong-version': '{"format_version":2,"n":1,"colors":[0]}',
        'NaN': '{"format_version":1,"n":1,"colors":[NaN]}',
        'infinity': '{"format_version":1,"n":1,"colors":[Infinity]}',
        'overflow': '{"format_version":1,"n":1e999,"colors":[0]}',
        'trailing-comma': '{"format_version":1,"n":1,"colors":[0,]}',
    }.items(): raw(name, value)
    raw('utf8-bom', b'\xef\xbb\xbf{"format_version":1,"n":1,"colors":[0]}')
    raw('invalid-utf8', b'\xff')
    raw('over-byte-cap', b' ' * (1024 * 1024 + 1))

    failures = []
    python_results = []
    for case in cases:
        result = verify(case['artifact'])
        python_results.append(result['valid'])
        if result['valid'] != case['expected'] or not witness_is_real(result, case['artifact']['colors']): failures.append('python:' + case['name'])
    for case in raw_cases:
        if verify_bytes(base64.b64decode(case['raw_b64']))['valid'] != case['expected']: failures.append('python:' + case['name'])

    runner = """import fs from 'node:fs';
import {verify,verifyBytes} from './verify.mjs';
const input=JSON.parse(fs.readFileSync(0,'utf8'));
const out=input.cases.map(c=>verify(c.artifact)).concat(input.raw.map(c=>verifyBytes(Buffer.from(c.raw_b64,'base64'))));
process.stdout.write(JSON.stringify(out));"""
    node = subprocess.run(['node', '--input-type=module', '-e', runner], input=json.dumps({'cases': cases, 'raw': raw_cases}), cwd=ROOT, text=True, encoding='utf-8', capture_output=True, check=True)
    node_results = json.loads(node.stdout)
    for case, result in zip(cases + raw_cases, node_results, strict=True):
        if result['valid'] != case['expected'] or ('artifact' in case and not witness_is_real(result, case['artifact']['colors'])): failures.append('node:' + case['name'])

    reference = None
    if args.reference_cnf:
        true_variables = {i * 6 + c + 1 for i, c in enumerate(baseline['colors'])}
        clauses, unsatisfied, header = 0, 0, None
        with args.reference_cnf.open() as stream:
            for line in stream:
                if not line.strip() or line.startswith('c '): continue
                if line.startswith('p '):
                    _, form, variables, count = line.split(); assert form == 'cnf'
                    header = [int(variables), int(count)]; continue
                literals = [int(x) for x in line.split()]
                assert literals[-1] == 0
                unsatisfied += not any((lit in true_variables) if lit > 0 else (-lit not in true_variables) for lit in literals[:-1])
                clauses += 1
        assert header == [3216, 439520] and clauses == header[1]
        if unsatisfied: failures.append('independent-reference-cnf')
        reference = dict(encoder_author='Marijn J. H. Heule', variables=header[0], clauses=clauses, unsatisfied=unsatisfied, cnf_sha256=hashlib.sha256(args.reference_cnf.read_bytes()).hexdigest())
    report = dict(baseline=verify_bytes(baseline_bytes), implementation_count=2,
                  algorithm_cases=len(cases), exhaustive_six_color_cases_up_to_n5=exhaustive_count,
                  random_cases=300, valid_baseline_prefixes=536, single_label_mutations=len(mutations),
                  mutation_oracle_valid=sum(c['expected'] for c in mutations), raw_format_cases=len(raw_cases),
                  all_case_evaluations=2*(len(cases)+len(raw_cases)), failures=failures,
                  independent_reference_cnf=reference,
                  checker_sha256={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in ['verify.py','verify.mjs','artifact.schema.json','build_baseline.py','source-transcription.json']},
                  limits='Finite tests and an independent published encoding corroborate checker behavior; this is not a formal correctness proof or independent-operator review.')
    args.output.write_bytes((json.dumps(report,indent=2)+'\n').encode('utf-8'))
    print(json.dumps(report,indent=2))
    return int(bool(failures))


if __name__ == '__main__':
    raise SystemExit(main())
